// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v5.26.1
// source: pkg/controller/functionstate.proto

package controller

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type FunctionInstanceRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionName string `protobuf:"bytes,1,opt,name=FunctionName,proto3" json:"FunctionName,omitempty"`
}

func (x *FunctionInstanceRequest) Reset() {
	*x = FunctionInstanceRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_controller_functionstate_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionInstanceRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInstanceRequest) ProtoMessage() {}

func (x *FunctionInstanceRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_controller_functionstate_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInstanceRequest.ProtoReflect.Descriptor instead.
func (*FunctionInstanceRequest) Descriptor() ([]byte, []int) {
	return file_pkg_controller_functionstate_proto_rawDescGZIP(), []int{0}
}

func (x *FunctionInstanceRequest) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

type FunctionInstanceResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url string `protobuf:"bytes,1,opt,name=Url,proto3" json:"Url,omitempty"`
}

func (x *FunctionInstanceResponse) Reset() {
	*x = FunctionInstanceResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_controller_functionstate_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FunctionInstanceResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FunctionInstanceResponse) ProtoMessage() {}

func (x *FunctionInstanceResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_controller_functionstate_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FunctionInstanceResponse.ProtoReflect.Descriptor instead.
func (*FunctionInstanceResponse) Descriptor() ([]byte, []int) {
	return file_pkg_controller_functionstate_proto_rawDescGZIP(), []int{1}
}

func (x *FunctionInstanceResponse) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type StreamClosedNotification struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FunctionName string `protobuf:"bytes,1,opt,name=FunctionName,proto3" json:"FunctionName,omitempty"`
	Url          string `protobuf:"bytes,2,opt,name=Url,proto3" json:"Url,omitempty"`
}

func (x *StreamClosedNotification) Reset() {
	*x = StreamClosedNotification{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_controller_functionstate_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamClosedNotification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamClosedNotification) ProtoMessage() {}

func (x *StreamClosedNotification) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_controller_functionstate_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamClosedNotification.ProtoReflect.Descriptor instead.
func (*StreamClosedNotification) Descriptor() ([]byte, []int) {
	return file_pkg_controller_functionstate_proto_rawDescGZIP(), []int{2}
}

func (x *StreamClosedNotification) GetFunctionName() string {
	if x != nil {
		return x.FunctionName
	}
	return ""
}

func (x *StreamClosedNotification) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type StreamClosedNotificationResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// TODO replace with something useful
	Ok bool `protobuf:"varint,1,opt,name=ok,proto3" json:"ok,omitempty"`
}

func (x *StreamClosedNotificationResponse) Reset() {
	*x = StreamClosedNotificationResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_controller_functionstate_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StreamClosedNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamClosedNotificationResponse) ProtoMessage() {}

func (x *StreamClosedNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_controller_functionstate_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamClosedNotificationResponse.ProtoReflect.Descriptor instead.
func (*StreamClosedNotificationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_controller_functionstate_proto_rawDescGZIP(), []int{3}
}

func (x *StreamClosedNotificationResponse) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

var File_pkg_controller_functionstate_proto protoreflect.FileDescriptor

var file_pkg_controller_functionstate_proto_rawDesc = []byte{
	0x0a, 0x22, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x2f, 0x66, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x74, 0x61, 0x74, 0x65, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72,
	0x22, 0x3d, 0x0a, 0x17, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x73, 0x74,
	0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0c, 0x46,
	0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x22,
	0x2c, 0x0a, 0x18, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x61,
	0x6e, 0x63, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x55,
	0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x22, 0x50, 0x0a,
	0x18, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x4e, 0x6f, 0x74,
	0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x22, 0x0a, 0x0c, 0x46, 0x75, 0x6e,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0c, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x10, 0x0a,
	0x03, 0x55, 0x72, 0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x55, 0x72, 0x6c, 0x22,
	0x32, 0x0a, 0x20, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x4e,
	0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x02, 0x6f, 0x6b, 0x32, 0xe0, 0x01, 0x0a, 0x16, 0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e,
	0x43, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5a,
	0x0a, 0x0b, 0x47, 0x65, 0x74, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x12, 0x23, 0x2e,
	0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x46, 0x75, 0x6e, 0x63, 0x74,
	0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x24, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e,
	0x46, 0x75, 0x6e, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x6e, 0x73, 0x74, 0x61, 0x6e, 0x63, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x6a, 0x0a, 0x12, 0x4e, 0x6f,
	0x74, 0x69, 0x66, 0x79, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64,
	0x12, 0x24, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x2e, 0x53, 0x74,
	0x72, 0x65, 0x61, 0x6d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64, 0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69,
	0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x1a, 0x2c, 0x2e, 0x63, 0x6f, 0x6e, 0x74, 0x72, 0x6f, 0x6c,
	0x6c, 0x65, 0x72, 0x2e, 0x53, 0x74, 0x72, 0x65, 0x61, 0x6d, 0x43, 0x6c, 0x6f, 0x73, 0x65, 0x64,
	0x4e, 0x6f, 0x74, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x10, 0x5a, 0x0e, 0x70, 0x6b, 0x67, 0x2f, 0x63, 0x6f,
	0x6e, 0x74, 0x72, 0x6f, 0x6c, 0x6c, 0x65, 0x72, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_controller_functionstate_proto_rawDescOnce sync.Once
	file_pkg_controller_functionstate_proto_rawDescData = file_pkg_controller_functionstate_proto_rawDesc
)

func file_pkg_controller_functionstate_proto_rawDescGZIP() []byte {
	file_pkg_controller_functionstate_proto_rawDescOnce.Do(func() {
		file_pkg_controller_functionstate_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_controller_functionstate_proto_rawDescData)
	})
	return file_pkg_controller_functionstate_proto_rawDescData
}

var file_pkg_controller_functionstate_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_pkg_controller_functionstate_proto_goTypes = []interface{}{
	(*FunctionInstanceRequest)(nil),          // 0: controller.FunctionInstanceRequest
	(*FunctionInstanceResponse)(nil),         // 1: controller.FunctionInstanceResponse
	(*StreamClosedNotification)(nil),         // 2: controller.StreamClosedNotification
	(*StreamClosedNotificationResponse)(nil), // 3: controller.StreamClosedNotificationResponse
}
var file_pkg_controller_functionstate_proto_depIdxs = []int32{
	0, // 0: controller.FunctionControlService.GetInstance:input_type -> controller.FunctionInstanceRequest
	2, // 1: controller.FunctionControlService.NotifyStreamClosed:input_type -> controller.StreamClosedNotification
	1, // 2: controller.FunctionControlService.GetInstance:output_type -> controller.FunctionInstanceResponse
	3, // 3: controller.FunctionControlService.NotifyStreamClosed:output_type -> controller.StreamClosedNotificationResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_controller_functionstate_proto_init() }
func file_pkg_controller_functionstate_proto_init() {
	if File_pkg_controller_functionstate_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_controller_functionstate_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionInstanceRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_controller_functionstate_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FunctionInstanceResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_controller_functionstate_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamClosedNotification); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_controller_functionstate_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StreamClosedNotificationResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_controller_functionstate_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_controller_functionstate_proto_goTypes,
		DependencyIndexes: file_pkg_controller_functionstate_proto_depIdxs,
		MessageInfos:      file_pkg_controller_functionstate_proto_msgTypes,
	}.Build()
	File_pkg_controller_functionstate_proto = out.File
	file_pkg_controller_functionstate_proto_rawDesc = nil
	file_pkg_controller_functionstate_proto_goTypes = nil
	file_pkg_controller_functionstate_proto_depIdxs = nil
}
